# ------------------------------------------------------------------ #
#                                                                    #
#           SymPy CI script for Github Actions                       #
#                                                                    #
#   Runs each time a pull request is opened, pushed or merged        #
#                                                                    #
# ------------------------------------------------------------------ #

name: test
on: [push, pull_request]
jobs:

  # -------------------- Code quality ------------------------------ #

  code-quality:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath flake8
      - run: bin/test quality
      - run: flake8 sympy
        # compileall is used to detect invalid escapes like '\e'
      - run: python -We:invalid -We::SyntaxWarning -m compileall -f -q sympy/
        # test all modules are listed in setup.py
      - run: bin/test_setup.py

  # -------------------- Doctests latest Python -------------------- #

  doctests-latest:
    needs: code-quality

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: bin/doctest --force-colors
      - run: examples/all.py -q

  # -------------------- Test split 1/2 latest Python -------------- #

  tests1-latest:
    needs: code-quality

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: bin/test --force-colors --split=1/2

  # -------------------- Test split 2/2 latest Python -------------- #

  tests2-latest:
    needs: code-quality

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: bin/test --force-colors --split=2/2

  # -------------------- Optional dependency tests ----------------- #

  optional-dependencies:
    needs: code-quality

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: sudo apt install antlr4 libgfortran5 gfortran libmpfr-dev libmpc-dev
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath gmpy2 matplotlib numpy scipy aesara ipython \
                         symengine cython llvmlite wurlitzer \
                         autowrap numexpr 'antlr4-python3-runtime==4.7.*'
      # Test external imports
      - run: bin/test_external_imports.py
      - run: bin/test_submodule_imports.py
      - run: bin/test_executable.py
      # Test modules with specific dependencies
      - run: bin/test_optional_dependencies.py

  # -------------------- Slow test split 1/2 ----------------------- #

  slow1:
    needs: [doctests-latest, tests1-latest, tests2-latest]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: TRAVIS_BUILD_NUMBER=true bin/test --force-colors --slow --timeout=595 --split=1/2

  # -------------------- Slow test split 2/2 ----------------------- #

  slow2:
    needs: [doctests-latest, tests1-latest, tests2-latest]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: TRAVIS_BUILD_NUMBER=true bin/test --force-colors --slow --timeout=595 --split=2/2

  # -------------------- Test split 1/2 older Python --------------- #

  tests1:
    needs: [doctests-latest, tests1-latest, tests2-latest]

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', 'pypy-3.6']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: bin/test --force-colors --split=1/2

  # -------------------- Test split 2/2 older Python --------------- #

  tests2:
    needs: [doctests-latest, tests1-latest, tests2-latest]

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', 'pypy-3.6']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: bin/test --force-colors --split=2/2

  # -------------------- Doctests older Python --------------------- #

  doctests:
    needs: [doctests-latest, tests1-latest, tests2-latest]

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', 'pypy-3.6']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install mpmath
      - run: bin/doctest --force-colors
      - run: examples/all.py -q

  # -------------------- Build the html/latex docs ----------------- #

  sphinx:
    needs: [doctests-latest, tests1-latest, tests2-latest]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: release/aptinstall.sh
      - run: pip install -r release/requirements.txt
      - run: bin/test_sphinx.sh


  # -------------------- Check the error message under py2 --------- #

  py2-import:
    needs: [doctests-latest, tests1-latest, tests2-latest]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - run: bin/test_py2_import.py
